# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage
default_platform(:ios)
setup_ci if ENV['CI']
import_certificate(
  certificate_path: "cert.p12",
  certificate_password: ENV["CERTIFICATE_PASSWORD"],
  keychain_name: ENV["MATCH_KEYCHAIN_NAME"]
)
# 2 provisioning profiles, 1 for the main app and 1 for the share extension
install_provisioning_profile(path: "buildpp.mobileprovision")
install_provisioning_profile(path: "shareextpp.mobileprovision")

platform :ios do
  desc "Build development version"
  lane :dev do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      code_sign_identity: "Apple Development"
    )
    # Update the provisioning profile for both the main app and extension
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: "./buildpp.mobileprovision",
      target_filter: ".*Runner.*"
    )
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: "./shareextpp.mobileprovision",
      target_filter: ".*LinshareShareExtension.*"
    )
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      codesigning_identity: "Apple Development: Nguyen Thai",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "com.linagora.ios.linshare": "linshare.development.profile",
          "com.linagora.ios.linshare.extension": "linshare.share.ext.development.profile"
        }
      }
    )
  end

  desc "Build and deploy release version"
  lane :release do
    latest_build_number = 100 # Hardcode for now
    version_number = last_git_tag.gsub("v", "")
    increment_build_number(
      build_number: latest_build_number + ENV['GITHUB_RUN_NUMBER'].to_i
    )
    increment_version_number(
      version_number: version_number
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      code_sign_identity: "Apple Distribution"
    )
    # Update the provisioning profile for both the main app and extension
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: "./buildpp.mobileprovision",
      target_filter: ".*Runner.*"
    )
    update_project_provisioning(
      xcodeproj: "Runner.xcodeproj",
      profile: "./shareextpp.mobileprovision",
      target_filter: ".*LinshareShareExtension.*"
    )
    build_app(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      codesigning_identity: "Apple Distribution: Linagora",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.linagora.ios.linshare": "linshare.distribution.profile",
          "com.linagora.ios.linshare.extension": "linshare.share.ext.distribution.profile"
        }
      }
    )
    # We don't have api keys, so using command line for now
    sh "xcrun altool --upload-app -f ../LinShare.ipa -t ios -u $FASTLANE_USER -p $FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"
    # upload_to_testflight(
    #   apple_id: ENV["APPLE_APP_ID"],
    #   skip_waiting_for_build_processing: true,
    #   ipa: "ios/LinShare.ipa"
    # )
  end
end
