// Mocks generated by Mockito 5.0.17 from annotations
// in data/test/network/quota_datasource_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;

import 'package:data/data.dart' as _i2;
import 'package:data/src/network/model/functionality/functionality_dto.dart'
    as _i15;
import 'package:data/src/network/model/request/copy_body_request.dart' as _i14;
import 'package:data/src/network/model/request/enable_versioning_work_group_body_request.dart'
    as _i16;
import 'package:data/src/network/model/request/permanent_token_body_request.dart'
    as _i11;
import 'package:data/src/network/model/request/share_document_body_request.dart'
    as _i13;
import 'package:data/src/network/model/response/account_quota_response.dart'
    as _i5;
import 'package:data/src/network/model/response/document_details_response.dart'
    as _i7;
import 'package:data/src/network/model/response/document_response.dart' as _i4;
import 'package:data/src/network/model/response/upload_request_group_response.dart'
    as _i8;
import 'package:data/src/network/model/response/user_response.dart' as _i12;
import 'package:data/src/network/model/sharedspacedocument/work_group_folder_dto.dart'
    as _i6;
import 'package:dio/dio.dart' as _i3;
import 'package:domain/domain.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePermanentToken_0 extends _i1.Fake implements _i2.PermanentToken {}

class _FakeResponseBody_1 extends _i1.Fake implements _i3.ResponseBody {}

class _FakeDocumentResponse_2 extends _i1.Fake implements _i4.DocumentResponse {
}

class _FakeWorkGroupNodeDto_3 extends _i1.Fake implements _i2.WorkGroupNodeDto {
}

class _FakeAccountQuotaResponse_4 extends _i1.Fake
    implements _i5.AccountQuotaResponse {}

class _FakeSharedSpaceNodeNestedResponse_5 extends _i1.Fake
    implements _i2.SharedSpaceNodeNestedResponse {}

class _FakeWorkGroupNodeFolderDto_6 extends _i1.Fake
    implements _i6.WorkGroupNodeFolderDto {}

class _FakeSharedSpaceMemberResponse_7 extends _i1.Fake
    implements _i2.SharedSpaceMemberResponse {}

class _FakeDocumentDetailsResponse_8 extends _i1.Fake
    implements _i7.DocumentDetailsResponse {}

class _FakeUploadRequestGroupResponse_9 extends _i1.Fake
    implements _i8.UploadRequestGroupResponse {}

class _FakeUploadRequestResponse_10 extends _i1.Fake
    implements _i2.UploadRequestResponse {}

class _FakeReceivedShareDto_11 extends _i1.Fake
    implements _i2.ReceivedShareDto {}

class _FakeUploadRequestEntryResponse_12 extends _i1.Fake
    implements _i2.UploadRequestEntryResponse {}

/// A class which mocks [LinShareHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinShareHttpClient extends _i1.Mock
    implements _i2.LinShareHttpClient {
  MockLinShareHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.PermanentToken> createPermanentToken(
          Uri? authenticateUrl,
          _i10.APIVersionSupported? apiVersion,
          String? userName,
          String? password,
          _i11.PermanentTokenBodyRequest? bodyRequest,
          {_i10.OTPCode? otpCode}) =>
      (super.noSuchMethod(
              Invocation.method(#createPermanentToken, [
                authenticateUrl,
                apiVersion,
                userName,
                password,
                bodyRequest
              ], {
                #otpCode: otpCode
              }),
              returnValue:
                  Future<_i2.PermanentToken>.value(_FakePermanentToken_0()))
          as _i9.Future<_i2.PermanentToken>);
  @override
  _i9.Future<_i2.PermanentToken> createPermanentTokenWithOIDC(
          Uri? authenticateUrl,
          _i10.APIVersionSupported? apiVersion,
          String? oidcToken,
          _i11.PermanentTokenBodyRequest? bodyRequest,
          {_i10.OTPCode? otpCode}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createPermanentTokenWithOIDC,
                  [authenticateUrl, apiVersion, oidcToken, bodyRequest],
                  {#otpCode: otpCode}),
              returnValue:
                  Future<_i2.PermanentToken>.value(_FakePermanentToken_0()))
          as _i9.Future<_i2.PermanentToken>);
  @override
  _i9.Future<bool> deletePermanentToken(_i2.PermanentToken? token) =>
      (super.noSuchMethod(Invocation.method(#deletePermanentToken, [token]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i12.UserResponse?> getAuthorizedUser() =>
      (super.noSuchMethod(Invocation.method(#getAuthorizedUser, []),
              returnValue: Future<_i12.UserResponse?>.value())
          as _i9.Future<_i12.UserResponse?>);
  @override
  _i9.Future<List<_i4.DocumentResponse>> getAllDocument() =>
      (super.noSuchMethod(Invocation.method(#getAllDocument, []),
              returnValue: Future<List<_i4.DocumentResponse>>.value(
                  <_i4.DocumentResponse>[]))
          as _i9.Future<List<_i4.DocumentResponse>>);
  @override
  _i9.Future<List<_i2.ShareDto>> shareDocument(
          _i13.ShareDocumentBodyRequest? bodyRequest) =>
      (super.noSuchMethod(Invocation.method(#shareDocument, [bodyRequest]),
              returnValue: Future<List<_i2.ShareDto>>.value(<_i2.ShareDto>[]))
          as _i9.Future<List<_i2.ShareDto>>);
  @override
  _i9.Future<_i3.ResponseBody> downloadFile(String? url,
          _i3.CancelToken? cancelToken, _i10.Token? permanentToken) =>
      (super.noSuchMethod(
          Invocation.method(#downloadFile, [url, cancelToken, permanentToken]),
          returnValue:
              Future<_i3.ResponseBody>.value(_FakeResponseBody_1())) as _i9
          .Future<_i3.ResponseBody>);
  @override
  _i9.Future<List<_i2.SharedSpaceNodeNestedResponse>> getSharedSpaces() =>
      (super.noSuchMethod(Invocation.method(#getSharedSpaces, []),
          returnValue: Future<List<_i2.SharedSpaceNodeNestedResponse>>.value(
              <_i2.SharedSpaceNodeNestedResponse>[])) as _i9
          .Future<List<_i2.SharedSpaceNodeNestedResponse>>);
  @override
  _i9.Future<List<_i2.AuditLogEntryUserDto?>> getSharedSpaceActivities(
          _i10.SharedSpaceId? sharedSpaceId) =>
      (super.noSuchMethod(
              Invocation.method(#getSharedSpaceActivities, [sharedSpaceId]),
              returnValue: Future<List<_i2.AuditLogEntryUserDto?>>.value(
                  <_i2.AuditLogEntryUserDto?>[]))
          as _i9.Future<List<_i2.AuditLogEntryUserDto?>>);
  @override
  _i9.Future<List<_i10.AutoCompleteResult>> getSharingAutoComplete(
          _i10.AutoCompletePattern? autoCompletePattern,
          _i10.AutoCompleteType? autoCompleteType,
          {_i10.ThreadId? threadId}) =>
      (super.noSuchMethod(
          Invocation.method(#getSharingAutoComplete,
              [autoCompletePattern, autoCompleteType], {#threadId: threadId}),
          returnValue: Future<List<_i10.AutoCompleteResult>>.value(
              <_i10.AutoCompleteResult>[])) as _i9.Future<List<_i10.AutoCompleteResult>>);
  @override
  _i9.Future<List<_i2.WorkGroupNodeDto>> getWorkGroupChildNodes(
          _i10.SharedSpaceId? sharedSpaceId,
          {_i10.WorkGroupNodeId? parentId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getWorkGroupChildNodes, [sharedSpaceId], {#parentId: parentId}),
          returnValue: Future<List<_i2.WorkGroupNodeDto>>.value(
              <_i2.WorkGroupNodeDto>[])) as _i9
          .Future<List<_i2.WorkGroupNodeDto>>);
  @override
  _i9.Future<List<_i10.ReceivedShare>> getReceivedShares() =>
      (super.noSuchMethod(Invocation.method(#getReceivedShares, []),
          returnValue: Future<List<_i10.ReceivedShare>>.value(
              <_i10.ReceivedShare>[])) as _i9.Future<List<_i10.ReceivedShare>>);
  @override
  _i9.Future<List<_i2.WorkGroupNodeDto>> copyWorkGroupNodeToSharedSpaceDestination(
          _i14.CopyBodyRequest? copyRequest,
          _i10.SharedSpaceId? destinationSharedSpaceId,
          {_i10.WorkGroupNodeId? destinationParentNodeId}) =>
      (super.noSuchMethod(
          Invocation.method(
              #copyWorkGroupNodeToSharedSpaceDestination,
              [copyRequest, destinationSharedSpaceId],
              {#destinationParentNodeId: destinationParentNodeId}),
          returnValue: Future<List<_i2.WorkGroupNodeDto>>.value(
              <_i2.WorkGroupNodeDto>[])) as _i9.Future<List<_i2.WorkGroupNodeDto>>);
  @override
  _i9.Future<_i4.DocumentResponse> removeDocument(
          _i10.DocumentId? documentId) =>
      (super.noSuchMethod(Invocation.method(#removeDocument, [documentId]),
              returnValue:
                  Future<_i4.DocumentResponse>.value(_FakeDocumentResponse_2()))
          as _i9.Future<_i4.DocumentResponse>);
  @override
  _i9.Future<_i4.DocumentResponse> renameDocument(_i10.DocumentId? documentId,
          _i10.RenameDocumentRequest? renameDocumentRequest) =>
      (super.noSuchMethod(
              Invocation.method(
                  #renameDocument, [documentId, renameDocumentRequest]),
              returnValue:
                  Future<_i4.DocumentResponse>.value(_FakeDocumentResponse_2()))
          as _i9.Future<_i4.DocumentResponse>);
  @override
  _i9.Future<_i2.WorkGroupNodeDto> removeSharedSpaceNode(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.WorkGroupNodeId? sharedSpaceNodeId) =>
      (super.noSuchMethod(
              Invocation.method(
                  #removeSharedSpaceNode, [sharedSpaceId, sharedSpaceNodeId]),
              returnValue:
                  Future<_i2.WorkGroupNodeDto>.value(_FakeWorkGroupNodeDto_3()))
          as _i9.Future<_i2.WorkGroupNodeDto>);
  @override
  _i9.Future<_i5.AccountQuotaResponse> findQuota(_i10.QuotaId? quotaUuid) =>
      (super.noSuchMethod(Invocation.method(#findQuota, [quotaUuid]),
              returnValue: Future<_i5.AccountQuotaResponse>.value(
                  _FakeAccountQuotaResponse_4()))
          as _i9.Future<_i5.AccountQuotaResponse>);
  @override
  _i9.Future<List<_i4.DocumentResponse>> copyToMySpace(
          _i14.CopyBodyRequest? copyRequest) =>
      (super.noSuchMethod(Invocation.method(#copyToMySpace, [copyRequest]),
              returnValue: Future<List<_i4.DocumentResponse>>.value(
                  <_i4.DocumentResponse>[]))
          as _i9.Future<List<_i4.DocumentResponse>>);
  @override
  _i9.Future<List<_i15.FunctionalityDto>> getAllFunctionality() =>
      (super.noSuchMethod(Invocation.method(#getAllFunctionality, []),
              returnValue: Future<List<_i15.FunctionalityDto>>.value(
                  <_i15.FunctionalityDto>[]))
          as _i9.Future<List<_i15.FunctionalityDto>>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> deleteSharedSpace(
          _i10.SharedSpaceId? sharedSpaceId) =>
      (super.noSuchMethod(
              Invocation.method(#deleteSharedSpace, [sharedSpaceId]),
              returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
                  _FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i6.WorkGroupNodeFolderDto> createSharedSpaceNodeFolder(
          _i10.SharedSpaceId? sharedSpaceId,
          _i2.CreateSharedSpaceNodeFolderRequest?
              createSharedSpaceNodeRequest) =>
      (super.noSuchMethod(
              Invocation.method(#createSharedSpaceNodeFolder,
                  [sharedSpaceId, createSharedSpaceNodeRequest]),
              returnValue: Future<_i6.WorkGroupNodeFolderDto>.value(
                  _FakeWorkGroupNodeFolderDto_6()))
          as _i9.Future<_i6.WorkGroupNodeFolderDto>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> getSharedSpace(
          _i10.SharedSpaceId? sharedSpaceId,
          {_i10.MembersParameter? membersParameter =
              _i10.MembersParameter.withMembers,
          _i10.RolesParameter? rolesParameter =
              _i10.RolesParameter.withRole}) =>
      (super.noSuchMethod(
              Invocation.method(#getSharedSpace, [
                sharedSpaceId
              ], {
                #membersParameter: membersParameter,
                #rolesParameter: rolesParameter
              }),
              returnValue:
                  Future<_i2.SharedSpaceNodeNestedResponse>.value(_FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<List<_i2.SharedSpaceMemberResponse>> getSharedSpaceMembers(
          _i10.SharedSpaceId? sharedSpaceId) =>
      (super.noSuchMethod(
              Invocation.method(#getSharedSpaceMembers, [sharedSpaceId]),
              returnValue: Future<List<_i2.SharedSpaceMemberResponse>>.value(
                  <_i2.SharedSpaceMemberResponse>[]))
          as _i9.Future<List<_i2.SharedSpaceMemberResponse>>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> createSharedSpaceWorkGroup(
          _i2.CreateWorkGroupBodyRequest? createWorkGroupBodyRequest) =>
      (super.noSuchMethod(
              Invocation.method(
                  #createSharedSpaceWorkGroup, [createWorkGroupBodyRequest]),
              returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
                  _FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i2.WorkGroupNodeDto> renameSharedSpaceNode(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.WorkGroupNodeId? sharedSpaceNodeId,
          _i2.RenameWorkGroupNodeBodyRequest? renameWorkGroupNodeBodyRequest) =>
      (super.noSuchMethod(
              Invocation.method(#renameSharedSpaceNode, [
                sharedSpaceId,
                sharedSpaceNodeId,
                renameWorkGroupNodeBodyRequest
              ]),
              returnValue:
                  Future<_i2.WorkGroupNodeDto>.value(_FakeWorkGroupNodeDto_3()))
          as _i9.Future<_i2.WorkGroupNodeDto>);
  @override
  _i9.Future<_i2.SharedSpaceMemberResponse> addSharedSpaceMember(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.AddSharedSpaceMemberRequest? request) =>
      (super.noSuchMethod(
          Invocation.method(#addSharedSpaceMember, [sharedSpaceId, request]),
          returnValue: Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7())) as _i9
          .Future<_i2.SharedSpaceMemberResponse>);
  @override
  _i9.Future<List<_i2.SharedSpaceRoleDto>> getSharedSpaceRoles(
          {_i10.LinShareNodeType? type}) =>
      (super.noSuchMethod(
              Invocation.method(#getSharedSpaceRoles, [], {#type: type}),
              returnValue: Future<List<_i2.SharedSpaceRoleDto>>.value(
                  <_i2.SharedSpaceRoleDto>[]))
          as _i9.Future<List<_i2.SharedSpaceRoleDto>>);
  @override
  _i9.Future<_i2.SharedSpaceMemberResponse> updateRoleSharedSpaceMember(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.UpdateSharedSpaceMemberRequest? request) =>
      (super.noSuchMethod(
              Invocation.method(
                  #updateRoleSharedSpaceMember, [sharedSpaceId, request]),
              returnValue: Future<_i2.SharedSpaceMemberResponse>.value(
                  _FakeSharedSpaceMemberResponse_7()))
          as _i9.Future<_i2.SharedSpaceMemberResponse>);
  @override
  _i9.Future<_i2.SharedSpaceMemberResponse> updateRoleDriveMember(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.UpdateDriveMemberRequest? request,
          {bool? isOverrideRoleForAll}) =>
      (super.noSuchMethod(
              Invocation.method(#updateRoleDriveMember, [
                sharedSpaceId,
                request
              ], {
                #isOverrideRoleForAll: isOverrideRoleForAll
              }),
              returnValue: Future<_i2.SharedSpaceMemberResponse>.value(
                  _FakeSharedSpaceMemberResponse_7()))
          as _i9.Future<_i2.SharedSpaceMemberResponse>);
  @override
  _i9.Future<_i2.SharedSpaceMemberResponse> updateRoleWorkspaceMember(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.UpdateWorkspaceMemberRequest? request,
          {bool? isOverrideRoleForAll}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #updateRoleWorkspaceMember,
                  [sharedSpaceId, request],
                  {#isOverrideRoleForAll: isOverrideRoleForAll}),
              returnValue: Future<_i2.SharedSpaceMemberResponse>.value(
                  _FakeSharedSpaceMemberResponse_7()))
          as _i9.Future<_i2.SharedSpaceMemberResponse>);
  @override
  _i9.Future<_i2.SharedSpaceMemberResponse> deleteSharedSpaceMember(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.SharedSpaceMemberId? sharedSpaceMemberId) =>
      (super.noSuchMethod(
          Invocation.method(
              #deleteSharedSpaceMember, [sharedSpaceId, sharedSpaceMemberId]),
          returnValue: Future<_i2.SharedSpaceMemberResponse>.value(
              _FakeSharedSpaceMemberResponse_7())) as _i9
          .Future<_i2.SharedSpaceMemberResponse>);
  @override
  _i9.Future<_i7.DocumentDetailsResponse> getDocument(
          _i10.DocumentId? documentId) =>
      (super.noSuchMethod(Invocation.method(#getDocument, [documentId]),
              returnValue: Future<_i7.DocumentDetailsResponse>.value(
                  _FakeDocumentDetailsResponse_8()))
          as _i9.Future<_i7.DocumentDetailsResponse>);
  @override
  _i9.Future<_i2.WorkGroupNodeDto> getWorkGroupNode(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.WorkGroupNodeId? workGroupNodeId,
          {bool? hasTreePath = false}) =>
      (super.noSuchMethod(
              Invocation.method(#getWorkGroupNode, [
                sharedSpaceId,
                workGroupNodeId
              ], {
                #hasTreePath: hasTreePath
              }),
              returnValue:
                  Future<_i2.WorkGroupNodeDto>.value(_FakeWorkGroupNodeDto_3()))
          as _i9.Future<_i2.WorkGroupNodeDto>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> renameWorkGroup(
          _i10.SharedSpaceId? sharedSpaceId,
          _i2.RenameWorkGroupBodyRequest? renameWorkGroupBodyRequest) =>
      (super.noSuchMethod(
          Invocation.method(
              #renameWorkGroup, [sharedSpaceId, renameWorkGroupBodyRequest]),
          returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5())) as _i9
          .Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> renameDrive(
          _i10.SharedSpaceId? sharedSpaceId,
          _i2.RenameDriveBodyRequest? renameDriveBodyRequest) =>
      (super.noSuchMethod(
              Invocation.method(
                  #renameDrive, [sharedSpaceId, renameDriveBodyRequest]),
              returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
                  _FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> renameWorkSpace(
          _i10.SharedSpaceId? sharedSpaceId,
          _i2.RenameWorkSpaceBodyRequest? bodyRequest) =>
      (super.noSuchMethod(
              Invocation.method(#renameWorkSpace, [sharedSpaceId, bodyRequest]),
              returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
                  _FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i4.DocumentResponse> editDescriptionDocument(
          _i10.DocumentId? documentId,
          _i10.EditDescriptionDocumentRequest? request) =>
      (super.noSuchMethod(
          Invocation.method(#editDescriptionDocument, [documentId, request]),
          returnValue: Future<_i4.DocumentResponse>.value(
              _FakeDocumentResponse_2())) as _i9.Future<_i4.DocumentResponse>);
  @override
  _i9.Future<List<_i8.UploadRequestGroupResponse>> getAllUploadRequestGroups(
          List<_i10.UploadRequestStatus>? status) =>
      (super.noSuchMethod(
              Invocation.method(#getAllUploadRequestGroups, [status]),
              returnValue: Future<List<_i8.UploadRequestGroupResponse>>.value(
                  <_i8.UploadRequestGroupResponse>[]))
          as _i9.Future<List<_i8.UploadRequestGroupResponse>>);
  @override
  _i9.Future<_i8.UploadRequestGroupResponse> addNewUploadRequest(
          _i10.UploadRequestCreationType? creationType,
          _i10.AddUploadRequest? addUploadRequest) =>
      (super.noSuchMethod(
              Invocation.method(
                  #addNewUploadRequest, [creationType, addUploadRequest]),
              returnValue: Future<_i8.UploadRequestGroupResponse>.value(
                  _FakeUploadRequestGroupResponse_9()))
          as _i9.Future<_i8.UploadRequestGroupResponse>);
  @override
  _i9.Future<List<_i2.UploadRequestResponse>> getAllUploadRequests(
          _i10.UploadRequestGroupId? uploadRequestGroupId) =>
      (super.noSuchMethod(
              Invocation.method(#getAllUploadRequests, [uploadRequestGroupId]),
              returnValue: Future<List<_i2.UploadRequestResponse>>.value(
                  <_i2.UploadRequestResponse>[]))
          as _i9.Future<List<_i2.UploadRequestResponse>>);
  @override
  _i9.Future<List<_i2.UploadRequestEntryResponse>> getAllUploadRequestEntries(
          _i10.UploadRequestId? uploadRequestId) =>
      (super.noSuchMethod(
              Invocation.method(#getAllUploadRequestEntries, [uploadRequestId]),
              returnValue: Future<List<_i2.UploadRequestEntryResponse>>.value(
                  <_i2.UploadRequestEntryResponse>[]))
          as _i9.Future<List<_i2.UploadRequestEntryResponse>>);
  @override
  _i9.Future<_i2.UploadRequestResponse> updateUploadRequestStatus(
          _i10.UploadRequestId? uploadRequestId,
          _i10.UploadRequestStatus? newStatus,
          {bool? copyToMySpace}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUploadRequestStatus, [
                uploadRequestId,
                newStatus
              ], {
                #copyToMySpace: copyToMySpace
              }),
              returnValue: Future<_i2.UploadRequestResponse>.value(
                  _FakeUploadRequestResponse_10()))
          as _i9.Future<_i2.UploadRequestResponse>);
  @override
  _i9.Future<_i2.ReceivedShareDto> getReceivedShare(
          _i10.ShareId? receivedShareId) =>
      (super.noSuchMethod(
          Invocation.method(#getReceivedShare, [receivedShareId]),
          returnValue: Future<_i2.ReceivedShareDto>.value(
              _FakeReceivedShareDto_11())) as _i9.Future<_i2.ReceivedShareDto>);
  @override
  _i9.Future<_i8.UploadRequestGroupResponse> addRecipientsToUploadRequestGroup(
          _i10.UploadRequestGroupId? uploadRequestGroupId,
          List<_i10.GenericUser>? recipients) =>
      (super.noSuchMethod(
              Invocation.method(#addRecipientsToUploadRequestGroup,
                  [uploadRequestGroupId, recipients]),
              returnValue: Future<_i8.UploadRequestGroupResponse>.value(
                  _FakeUploadRequestGroupResponse_9()))
          as _i9.Future<_i8.UploadRequestGroupResponse>);
  @override
  _i9.Future<_i8.UploadRequestGroupResponse> updateUploadRequestGroupStatus(
          _i10.UploadRequestGroupId? uploadRequestGroupId,
          _i10.UploadRequestStatus? status,
          {bool? copyToMySpace}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUploadRequestGroupStatus, [
                uploadRequestGroupId,
                status
              ], {
                #copyToMySpace: copyToMySpace
              }),
              returnValue: Future<_i8.UploadRequestGroupResponse>.value(
                  _FakeUploadRequestGroupResponse_9()))
          as _i9.Future<_i8.UploadRequestGroupResponse>);
  @override
  _i9.Future<List<_i2.AuthenticationAuditLogEntryUserResponse>>
      getAuditAuthenticationEntryUser() => (super.noSuchMethod(
          Invocation.method(#getAuditAuthenticationEntryUser, []),
          returnValue:
              Future<List<_i2.AuthenticationAuditLogEntryUserResponse>>.value(
                  <_i2.AuthenticationAuditLogEntryUserResponse>[])) as _i9
          .Future<List<_i2.AuthenticationAuditLogEntryUserResponse>>);
  @override
  _i9.Future<_i2.WorkGroupNodeDto> moveWorkgroupNode(
          _i2.MoveWorkGroupNodeBodyRequest? moveRequest,
          _i10.SharedSpaceId? sourceSharedSpaceId) =>
      (super.noSuchMethod(
              Invocation.method(
                  #moveWorkgroupNode, [moveRequest, sourceSharedSpaceId]),
              returnValue:
                  Future<_i2.WorkGroupNodeDto>.value(_FakeWorkGroupNodeDto_3()))
          as _i9.Future<_i2.WorkGroupNodeDto>);
  @override
  _i9.Future<_i2.ReceivedShareDto> removeReceivedShare(_i10.ShareId? shareId) =>
      (super.noSuchMethod(Invocation.method(#removeReceivedShare, [shareId]),
          returnValue: Future<_i2.ReceivedShareDto>.value(
              _FakeReceivedShareDto_11())) as _i9.Future<_i2.ReceivedShareDto>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> enableVersioningWorkGroup(
          _i10.SharedSpaceId? sharedSpaceId,
          _i16.EnableVersioningWorkGroupBodyRequest?
              enableVersioningBodyRequest) =>
      (super.noSuchMethod(
              Invocation.method(#enableVersioningWorkGroup,
                  [sharedSpaceId, enableVersioningBodyRequest]),
              returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
                  _FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<List<_i2.WorkGroupNodeDto>> advanceSearchWorkGroupNodes(
          _i10.SharedSpaceId? sharedSpaceId,
          _i10.AdvancedSearchRequest? searchRequest) =>
      (super.noSuchMethod(
              Invocation.method(
                  #advanceSearchWorkGroupNodes, [sharedSpaceId, searchRequest]),
              returnValue: Future<List<_i2.WorkGroupNodeDto>>.value(
                  <_i2.WorkGroupNodeDto>[]))
          as _i9.Future<List<_i2.WorkGroupNodeDto>>);
  @override
  bool validateSearchResult(Map<String, dynamic>? jsonResult) => (super
      .noSuchMethod(Invocation.method(#validateSearchResult, [jsonResult]),
          returnValue: false) as bool);
  @override
  _i9.Future<String> getOIDCConfiguration(Uri? baseUrl) =>
      (super.noSuchMethod(Invocation.method(#getOIDCConfiguration, [baseUrl]),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i2.UploadRequestEntryResponse> removeUploadRequestEntry(
          _i10.UploadRequestEntryId? entryId) =>
      (super.noSuchMethod(
              Invocation.method(#removeUploadRequestEntry, [entryId]),
              returnValue: Future<_i2.UploadRequestEntryResponse>.value(
                  _FakeUploadRequestEntryResponse_12()))
          as _i9.Future<_i2.UploadRequestEntryResponse>);
  @override
  _i9.Future<_i8.UploadRequestGroupResponse> editUploadRequest(
          _i10.UploadRequestGroupId? uploadRequestGroupId,
          _i10.EditUploadRequest? request) =>
      (super.noSuchMethod(
              Invocation.method(
                  #editUploadRequest, [uploadRequestGroupId, request]),
              returnValue: Future<_i8.UploadRequestGroupResponse>.value(
                  _FakeUploadRequestGroupResponse_9()))
          as _i9.Future<_i8.UploadRequestGroupResponse>);
  @override
  _i9.Future<List<_i2.SharedSpaceNodeNestedResponse>> getAllWorkgroups(
          _i10.SharedSpaceId? parentId) =>
      (super.noSuchMethod(Invocation.method(#getAllWorkgroups, [parentId]),
          returnValue: Future<List<_i2.SharedSpaceNodeNestedResponse>>.value(
              <_i2.SharedSpaceNodeNestedResponse>[])) as _i9
          .Future<List<_i2.SharedSpaceNodeNestedResponse>>);
  @override
  _i9.Future<_i2.UploadRequestResponse> getUploadRequest(
          _i10.UploadRequestId? uploadRequestId) =>
      (super.noSuchMethod(
              Invocation.method(#getUploadRequest, [uploadRequestId]),
              returnValue: Future<_i2.UploadRequestResponse>.value(
                  _FakeUploadRequestResponse_10()))
          as _i9.Future<_i2.UploadRequestResponse>);
  @override
  _i9.Future<_i2.UploadRequestResponse> editUploadRequestRecipient(
          _i10.UploadRequestId? uploadRequestId,
          _i10.EditUploadRequestRecipient? request) =>
      (super.noSuchMethod(
              Invocation.method(
                  #editUploadRequestRecipient, [uploadRequestId, request]),
              returnValue: Future<_i2.UploadRequestResponse>.value(
                  _FakeUploadRequestResponse_10()))
          as _i9.Future<_i2.UploadRequestResponse>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> createNewDrive(
          _i2.CreateDriveBodyRequest? createDriveBodyRequest) =>
      (super.noSuchMethod(
              Invocation.method(#createNewDrive, [createDriveBodyRequest]),
              returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
                  _FakeSharedSpaceNodeNestedResponse_5()))
          as _i9.Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i2.SharedSpaceNodeNestedResponse> createNewWorkSpace(
          _i2.CreateWorkSpaceBodyRequest? createWorkSpaceBodyRequest) =>
      (super.noSuchMethod(
          Invocation.method(#createNewWorkSpace, [createWorkSpaceBodyRequest]),
          returnValue: Future<_i2.SharedSpaceNodeNestedResponse>.value(
              _FakeSharedSpaceNodeNestedResponse_5())) as _i9
          .Future<_i2.SharedSpaceNodeNestedResponse>);
  @override
  _i9.Future<_i8.UploadRequestGroupResponse> getUploadRequestGroup(
          _i10.UploadRequestGroupId? uploadRequestGroupId) =>
      (super.noSuchMethod(
              Invocation.method(#getUploadRequestGroup, [uploadRequestGroupId]),
              returnValue: Future<_i8.UploadRequestGroupResponse>.value(
                  _FakeUploadRequestGroupResponse_9()))
          as _i9.Future<_i8.UploadRequestGroupResponse>);
  @override
  _i9.Future<List<_i2.AuditLogEntryUserDto?>> getUploadRequestActivities(
          _i10.UploadRequestId? uploadRequestId) =>
      (super.noSuchMethod(
              Invocation.method(#getUploadRequestActivities, [uploadRequestId]),
              returnValue: Future<List<_i2.AuditLogEntryUserDto?>>.value(
                  <_i2.AuditLogEntryUserDto?>[]))
          as _i9.Future<List<_i2.AuditLogEntryUserDto?>>);
  @override
  _i9.Future<List<_i2.AuditLogEntryUserDto?>> getUploadRequestEntryActivities(
          _i10.UploadRequestEntryId? entryId) =>
      (super.noSuchMethod(
              Invocation.method(#getUploadRequestEntryActivities, [entryId]),
              returnValue: Future<List<_i2.AuditLogEntryUserDto?>>.value(
                  <_i2.AuditLogEntryUserDto?>[]))
          as _i9.Future<List<_i2.AuditLogEntryUserDto?>>);
}
