// Mocks generated by Mockito 5.0.17 from annotations
// in domain/test/usecases/authenticationsso/create_permanent_token_sso_interactor_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeToken_0 extends _i1.Fake implements _i2.Token {}

class _FakeUri_1 extends _i1.Fake implements Uri {}

class _FakeSaaSSecretToken_2 extends _i1.Fake implements _i2.SaaSSecretToken {}

class _FakeUserSaaS_3 extends _i1.Fake implements _i2.UserSaaS {}

/// A class which mocks [TokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenRepository extends _i1.Mock implements _i2.TokenRepository {
  MockTokenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> persistToken(_i2.Token? token) =>
      (super.noSuchMethod(Invocation.method(#persistToken, [token]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> removeToken() =>
      (super.noSuchMethod(Invocation.method(#removeToken, []),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<_i2.Token> getToken() =>
      (super.noSuchMethod(Invocation.method(#getToken, []),
              returnValue: Future<_i2.Token>.value(_FakeToken_0()))
          as _i3.Future<_i2.Token>);
}

/// A class which mocks [CredentialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCredentialRepository extends _i1.Mock
    implements _i2.CredentialRepository {
  MockCredentialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> saveBaseUrl(Uri? baseUrl) =>
      (super.noSuchMethod(Invocation.method(#saveBaseUrl, [baseUrl]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> removeBaseUrl() =>
      (super.noSuchMethod(Invocation.method(#removeBaseUrl, []),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<Uri> getBaseUrl() =>
      (super.noSuchMethod(Invocation.method(#getBaseUrl, []),
          returnValue: Future<Uri>.value(_FakeUri_1())) as _i3.Future<Uri>);
}

/// A class which mocks [APIRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIRepository extends _i1.Mock implements _i2.APIRepository {
  MockAPIRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> persistAPIVersionSupported(
          _i2.APIVersionSupported? apiVersionSupported) =>
      (super.noSuchMethod(
          Invocation.method(#persistAPIVersionSupported, [apiVersionSupported]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<_i2.APIVersionSupported> getAPIVersionSupported() =>
      (super.noSuchMethod(Invocation.method(#getAPIVersionSupported, []),
              returnValue: Future<_i2.APIVersionSupported>.value(
                  _i2.APIVersionSupported.v5))
          as _i3.Future<_i2.APIVersionSupported>);
}

/// A class which mocks [AuthenticationOIDCRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationOIDCRepository extends _i1.Mock
    implements _i2.AuthenticationOIDCRepository {
  MockAuthenticationOIDCRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.TokenOIDC?> getTokenOIDC(
          String? clientId,
          String? redirectUrl,
          String? discoveryUrl,
          List<String>? scopes,
          bool? preferEphemeralSessionIOS,
          List<String>? promptValues,
          bool? allowInsecureConnections) =>
      (super.noSuchMethod(
              Invocation.method(#getTokenOIDC, [
                clientId,
                redirectUrl,
                discoveryUrl,
                scopes,
                preferEphemeralSessionIOS,
                promptValues,
                allowInsecureConnections
              ]),
              returnValue: Future<_i2.TokenOIDC?>.value())
          as _i3.Future<_i2.TokenOIDC?>);
  @override
  _i3.Future<void> persistTokenOIDC(_i2.TokenOIDC? tokenOidc) =>
      (super.noSuchMethod(Invocation.method(#persistTokenOIDC, [tokenOidc]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<_i2.TokenOIDC?> getStoredTokenOIDC() =>
      (super.noSuchMethod(Invocation.method(#getStoredTokenOIDC, []),
              returnValue: Future<_i2.TokenOIDC?>.value())
          as _i3.Future<_i2.TokenOIDC?>);
  @override
  _i3.Future<_i2.Token> createPermanentTokenWithOIDC(Uri? baseUrl,
          _i2.APIVersionSupported? apiVersion, _i2.TokenOIDC? tokenOIDC,
          {_i2.OTPCode? otpCode}) =>
      (super.noSuchMethod(
              Invocation.method(#createPermanentTokenWithOIDC,
                  [baseUrl, apiVersion, tokenOIDC], {#otpCode: otpCode}),
              returnValue: Future<_i2.Token>.value(_FakeToken_0()))
          as _i3.Future<_i2.Token>);
  @override
  _i3.Future<_i2.OIDCConfiguration?> getOIDCConfiguration(Uri? baseUrl) =>
      (super.noSuchMethod(Invocation.method(#getOIDCConfiguration, [baseUrl]),
              returnValue: Future<_i2.OIDCConfiguration?>.value())
          as _i3.Future<_i2.OIDCConfiguration?>);
  @override
  _i3.Future<_i2.SaaSSecretToken> getSaaSSecretToken(
          Uri? baseUrl, _i2.PlanRequest? planRequest) =>
      (super.noSuchMethod(
              Invocation.method(#getSaaSSecretToken, [baseUrl, planRequest]),
              returnValue:
                  Future<_i2.SaaSSecretToken>.value(_FakeSaaSSecretToken_2()))
          as _i3.Future<_i2.SaaSSecretToken>);
  @override
  _i3.Future<bool> verifyEmailSaaS(Uri? baseUrl, String? email) =>
      (super.noSuchMethod(Invocation.method(#verifyEmailSaaS, [baseUrl, email]),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
  @override
  _i3.Future<_i2.UserSaaS> signUpForSaaS(
          Uri? baseUrl, _i2.SignUpRequest? signUpRequest) =>
      (super.noSuchMethod(
              Invocation.method(#signUpForSaaS, [baseUrl, signUpRequest]),
              returnValue: Future<_i2.UserSaaS>.value(_FakeUserSaaS_3()))
          as _i3.Future<_i2.UserSaaS>);
  @override
  _i3.Future<void> logout(Uri? baseUrl) =>
      (super.noSuchMethod(Invocation.method(#logout, [baseUrl]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> deleteStoredTokenOIDC() =>
      (super.noSuchMethod(Invocation.method(#deleteStoredTokenOIDC, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
